# Generated by Django 3.0.6 on 2020-05-26 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200527_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexad', to='goods.GoodsCategory', verbose_name='类别')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexad', to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '首页商品类别广告',
                'verbose_name_plural': '首页商品类别广告',
            },
        ),
    ]
