# Generated by Django 3.0.6 on 2020-05-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0007_auto_20200525_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (2, '投诉'), (3, '询问'), (4, '售后'), (5, '求购')], default=1, help_text='留言类型：1(留言),2(投诉),3(询问),4(售后),5(求购)', verbose_name='留言类型'),
        ),
    ]
